---
title: "jhc_testing"
author: "Jay-Ho Chung"
date: "3/19/2018"
output: html_document
---

```{r, include=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r}
library(tidyverse)
library(gridExtra)
library(dplyr)
library(ggplot2)
library(ggthemes)
```

```{r}
# Filtering out contributions that were against a candidate
negative_contributions <- contributions %>% 
  filter(transaction_type == "24A")

# Filtering out contributions that were for a candidate
positive_contributions <- contributions %>% 
  filter(transaction_type == "24E")

# Renaming a fec_id to cand_id for joining
h_elections <- house_elections %>% 
  rename(cand_id = fec_id)

# Finding candidates that were funded against
negative_candidates <- inner_join(negative_contributions, candidates, by = "cand_id") %>% 

  right_join(h_elections , by = "cand_id") %>% # Linking the candidates to their names, not just id number
  filter(!is.na(transaction_type)) %>% # Do not want NA transactions
  filter(!is.na(transaction_type)) %>% 
  group_by(cand_name, cand_party_affiliation, primary_votes,
           runoff_votes, general_votes, ge_winner) %>% 
  summarize(total_dollars = sum(transaction_amt)) %>% 
  arrange(desc(total_dollars))

positive_candidates <- inner_join(positive_contributions, candidates, by = "cand_id") %>% 
  right_join(h_elections, by = "cand_id") %>% 
  filter(!is.na(transaction_type)) %>% 
  group_by(cand_name, cand_party_affiliation, primary_votes,
  runoff_votes, general_votes, ge_winner) %>%
  summarize(total_dollars = sum(transaction_amt)) %>% 
  arrange(desc(total_dollars)) 


ggplot(positive_candidates, aes(x = general_votes,
                                y = total_dollars)) +
  geom_point(aes(col = ge_winner))

ggplot(negative_candidates, aes(x = general_votes,
                                y = total_dollars)) +
  geom_point(aes(col = ge_winner))
```

So a few things. First, connect with the contributions and candidates.

```{r}
cand_contributions <- contributions %>%
  full_join(candidates , by = "cand_id") %>%
  group_by(cand_id , cand_name , cand_office_state , cmte_id , transaction_amt , transaction_dt , transaction_pgi , transaction_type)

h_elections <- house_elections %>% 
  rename(cand_id = fec_id)

hcand_contributions <- cand_contributions %>%
  full_join(h_elections , by = "cand_id")


n_cobn <- cand_contributions %>%
  select(cand_id , cand_name , cand_office_state , cand_party_affiliation , cand_office_district , cmte_id , transaction_amt , transaction_dt , transaction_pgi , transaction_type , entity_type) %>%
  filter(transaction_type == "24A" , entity_type == "ORG" , transaction_pgi == "G" , cand_office_state == "US")

p_cobn <- cand_contributions %>%
  select(cand_id , cand_name , cand_office_state , cand_party_affiliation , cand_office_district , cmte_id , transaction_amt , transaction_dt , transaction_pgi , transaction_type , entity_type) %>%
  filter(transaction_type == "24E" , entity_type == "ORG")

# This is just to find how many elections there were in total: 445. Phew.
house_elections %>%
  group_by(state , district) %>%
  summarize( N = n()) %>%
  nrow()
```



```{r}
n_cobn1 <- n_cobn %>% 
  group_by(cand_name) %>% 
  summarize(total_amt = sum(transaction_amt))

p_cobn1 <- p_cobn %>% 
  group_by(cand_name) %>% 
  summarize(total_amt = sum(transaction_amt)) %>% 
  arrange(desc(total_amt))

```

```{r}
hcand_dollars <- hcand_contributions %>% 
  filter(!is.na(cand_party_affiliation)) %>% 
  filter(!is.na(transaction_amt)) %>% 
  group_by(cand_party_affiliation) %>% 
  summarize(total_donations = sum(transaction_amt)) %>% 
  #filtered by certain parties but still 
  #doesn't look great on graph
  filter(cand_party_affiliation %in% c("DFL", "DEM", 
                                       "REP","IND"))
```

```{r}
hcand_wins <- hcand_contributions %>% 
  filter(!is.na(cand_party_affiliation), !is.na(ge_winner)) %>% 
  ungroup() %>% 
  select(cand_party_affiliation, candidate_name,
         ge_winner) %>% 
  group_by(candidate_name) %>% 
  unique() %>% 
  group_by(cand_party_affiliation) %>% 
  summarize(total = n_distinct(candidate_name), 
            wins = sum(ifelse(ge_winner == "W", 1, 0)),
            prop = wins/total)

hcand_wins1 <- hcand_wins %>% 
  #similarly filtered by only certain parties
  filter(cand_party_affiliation %in% c("DFL", "DEM", "REP",
                                       "UNK", "IND"))
```

```{r}
# basic plots showing success of parties in elections,
# as well as total donations received--not sure what we want to
# do here as only democrats and republicans receive much money
t_wins <- ggplot(hcand_wins1, aes(x = cand_party_affiliation, y = prop)) +
  geom_bar(stat = "identity") +
  theme_economist() +
  ggtitle("Proportions of Wins for Each Party") +
  labs(x = "Party Affiliation" , y = "Proportion")

t_dollars <- ggplot(hcand_dollars, aes(x = cand_party_affiliation, 
                          y = total_donations)) +
  geom_bar(stat = "identity") +
  theme_economist() +
  labs(x = "Party Affiliation" , y = "Total Donations")

t_wins
t_dollars
```

